const express=require('express')

const app=express()
var cors=require('cors')
const db=require('./config/database')
const userRouter=require('./router/userRouter')
const facebookRouter=require('./router/facebookRouter')
const productRouter=require('./router/productRouter')
const orderRouter=require('./router/orderRouter')
const catalogRouter=require('./router/catalogRouter')
const vendeurRouter=require('./router/vendeurRouter')
const clientRouter=require('./router/clientRouter')
var swagger=require('swagger-ui-express')
var swaggerdocument=require('./config/swagger.json')
var bodyParser=require('body-parser')
app.set("secretkey","chayma")
app.use(cors())
app.use(bodyParser.urlencoded({extended:false}))
app.use(bodyParser.json())
app.use('/vendeur',vendeurRouter)
app.use('/client',clientRouter)
app.use('/users',userRouter)
app.use('/facebook',facebookRouter)
app.use('/product',productRouter)
app.use('/order',orderRouter)
app.use('/catalog',catalogRouter)
app.use('/api',swagger.serve,swagger.setup(swaggerdocument))
app.get('/getfile/:photo',function(req,res){
    res.sendFile(__dirname+'/uploads/'+req.params.photo)
})
app.listen(3000,function(){
    console.log('runningwith 3000')
})